### ISSUE TITLE
compile.sh error

### ISSUE THREAD

**Issue by XP-CHRC** [HandsomeHans/Easy-LAB#2]
In file included from /home/xp/Downloads/LAB-master/include/caffe/caffe.hpp:7:0,                  from ./LAB.cpp:4: /home/xp/Downloads/LAB-master/include/caffe/blob.hpp:9:34: fatal error: caffe/proto/caffe.pb.h: No such file or directory compilation terminated.compil+: error: ./LAB.o: No such file or directory

I have copy LAB.cpp to ./tools, not move.
so how should i do?
Thanks.

**Comment by HansRen1024** [comment]
Hi @XP-CHRC, have you complied caffe by running "make all -j8". What is more, LAB.cpp and compile.sh should be in the same directory.
